const tourData = [
  {
    date: "Dec 16",
    showDate: "2025-12-16",
    city: "DETROIT, MI",
    venue: "DTE ENERGY MUSIC THEATRE",
    ticketLink: "",
  },
  {
    date: "Dec 19",
    showDate: "2025-12-19",
    city: "TORONTO, ON",
    venue: "BUDWEISER STAGE",
    ticketLink: "",
  },
  {
    date: "Dec 22",
    showDate: "2025-12-22",
    city: "BRISTOW, VA",
    venue: "",
    ticketLink: "",
  },
  {
    date: "Dec 29",
    showDate: "2025-12-29",
    city: "PHOENIX, AZ",
    venue: "AK-CHIN PAVILION",
    ticketLink: "",
  },
  {
    date: "Dec 2",
    showDate: "2025-12-02",
    city: "LAS VEGAS, NV",
    venue: "T-MOBILE ARENA",
    ticketLink: "",
  },
  {
    date: "Dec 7",
    showDate: "2025-12-07",
    city: "CONCORD, CA",
    venue: "CONCORD PAVILION",
    ticketLink: "",
  },
  {
    date: "Jan 16",
    showDate: "2026-01-16",
    city: "DETROIT, MI",
    venue: "DTE ENERGY MUSIC THEATRE",
    ticketLink: "",
  },
  {
    date: "Jan 19",
    showDate: "2026-01-19",
    city: "TORONTO, ON",
    venue: "BUDWEISER STAGE",
    ticketLink: "",
  },
  {
    date: "Jan 22",
    showDate: "2026-01-22",
    city: "BRISTOW, VA",
    venue: "",
    ticketLink: "",
  },
  {
    date: "Jan 29",
    showDate: "2026-01-29",
    city: "PHOENIX, AZ",
    venue: "AK-CHIN PAVILION",
    ticketLink: "",
  },
  {
    date: "Feb 2",
    showDate: "2026-02-02",
    city: "LAS VEGAS, NV",
    venue: "T-MOBILE ARENA",
    ticketLink: "",
  },
  {
    date: "Feb 7",
    showDate: "2026-02-07",
    city: "CONCORD, CA",
    venue: "CONCORD PAVILION",
    ticketLink: "",
  },
];

export default tourData;
